# Generated by Django 5.1.1 on 2024-10-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostsetting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='creator_email',
            field=models.EmailField(default='default@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='event_image',
            field=models.URLField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTftcCEqozA1cVgSpO4A6mJ2i-zD8MGLH0f9w&s'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='if_rsvp',
            field=models.BooleanField(default=False),
        ),
    ]
