# Generated by Django 5.1.1 on 2024-10-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostsetting', '0003_seed_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='if_matched',
            field=models.BooleanField(default=False),
        ),
    ]
