# Generated by Django 5.1.1 on 2024-10-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostsetting', '0006_alter_volunteerhistory_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdetails',
            name='if_matched',
        ),
        migrations.RemoveField(
            model_name='eventdetails',
            name='if_rsvp',
        ),
        migrations.AddField(
            model_name='volunteerhistory',
            name='matched_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='volunteerhistory',
            unique_together={('user', 'event')},
        ),
    ]
